### ISSUE TITLE
Decide game framework

### ISSUE THREAD

**Issue by Matthew-Rickman** [binzb8294/Shadows-of-The-Dragon#2]

**Comment by binzb8294** [comment]
Step 1 – Goals: Start with clear goals linked to strategic outcomes, such as increasing conversion rates. Goal-setting ensures a top-down analysis essential for developing effective metrics.

Step 2 – Actions: Identify user actions you want to influence to achieve these goals. Begin with a qualitative list of desired behaviors, such as converting free users to paid subscribers.

Step 3 – Metrics: Translate user actions into measurable metrics. Collaborate with data and engineering teams to ensure feasibility. Consider whether metrics should be tracked directly or through proxies, whether to aggregate data, and whether to focus on magnitude or ratios.

Step 4 – Evaluating Metrics: Test and iterate on your metrics by collecting data. Monitor their functional usefulness, identifying real product issues when metrics change. Adjustments should be made based on how metrics behave.

Conclusion: It's crucial to establish metrics before product development rather than retroactively. Doing so helps maintain focus, aligns team goals, holds product managers accountable, and supports objective decision-making during product launches.

**Comment by binzb8294** [comment]
Game Framework is pygame in python
